linters:
  disable-all: false
  enable-all: true
  disable:
    # Deprecated or auto disabled for lack of generics support
    - deadcode
    - scopelint
    - exhaustivestruct
    - maligned
    - interfacer
    - varcheck
    - golint
    - ifshort
    - structcheck
    - nosnakecase

    # Too annoying
    - exhaustruct # this is fine without, usually
    - funlen # somewhat ridiculous
    - cyclop # who cares! :D
    - godox # just leave it alone
    # Not now
    - paralleltest
    # TODO(apostasie) Temporary out until we wrap up all of them
    - wrapcheck

linters-settings:
  staticcheck:
    checks:
      - "all"

  depguard:
    rules:
      main:
        files:
          - "$all"
        allow:
          - $gostd
          - go.farcloser.world
          - github.com/grandcat/zeroconf
          - github.com/miekg/dns
          - golang.org/x/net/ipv4
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package